### ISSUE TITLE
NTP deamon ?

### ISSUE THREAD

**Issue by chrisribe** [geerlingguy/turing-pi-2-cluster#16]
Not critical of course but I was wondering if you experienced time offset issues ?
Having multiple Raspberry Pis running with databases etc how do you keep their clocks in sync ?

I did not seee an ntp deamon or other there so I was curious.

BTW great work ! 

I am amazed at the quality of your videos, editing and code to boot.
How do you do it ??

**Comment by geerlingguy** [comment]
I actually haven't had issues so far—even though the board has an RTC + battery it can't use them yet (firmware is still prototype).

What happens is immediately after Pi OS gets a network connection, it pulls down the time/date using `timesyncd` automatically (no extra setup needed in this playbook). I think it might also use fake-hwclock or something like that to save the last time after a shutdown so it's a little closer to reality (instead of epoch).

Eventually I would also like to configure the cluster to use the RTC on the Turing Pi 2 board for this purpose.

How do I do it? Good question :D

**Comment by chrisribe** [comment]
Ah it uses timesyncd in the the PI image !
I scanned the playbook and did not see any time stuff, so that's why I asked about it.

Learned something new today, thanks !
https://unix.stackexchange.com/questions/305643/ntpd-vs-systemd-timesyncd-how-to-achieve-reliable-ntp-syncing
